source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Beakn_Example', :exclusive => true do
  pod "Beakn", :path => "../"
end

target 'Beakn_Tests', :exclusive => true do
  pod "Beakn", :path => "../"

  
end
